import { useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, AlertOctagon, Check, CheckCircle2, ChevronRight, CircleAlert, Copy, RefreshCw, Search, Server, Siren, TerminalSquare } from 'lucide-react'
import { api } from '../api/client'
import { AppShell } from '../components/AppShell'
import { Badge, Button, EmptyState, ErrorState, Input, Select, Textarea, useOverlayKeys } from '../components/UI'
import { useToast } from '../components/Toast'
import { useBrand } from '../branding/BrandContext'
import { buildNote } from './incidentbuild'
import type { ServerError } from '../types'
import { copyText, displayError, formatDate, relativeDate } from '../utils'

const severityTone = { critical: 'danger', high: 'warning', medium: 'info', low: 'neutral' } as const
const severityLabel = { critical: 'Critical', high: 'High', medium: 'Medium', low: 'Low' }

export function AdminErrorsPage() {
  // The build this deployment is running, to read a record against.
  const { version: runningVersion } = useBrand()
  const [errors, setErrors] = useState<ServerError[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('open')
  const [severity, setSeverity] = useState('all')
  const [selected, setSelected] = useState<ServerError | null>(null)
  // The drawer is a dialog like any other: Escape closes it, Tab stays in it,
  // and the row that opened it gets the keyboard back.
  const drawer = useOverlayKeys(Boolean(selected), () => setSelected(null))
  const [working, setWorking] = useState(false)
  const { showToast } = useToast()
  const load = useCallback(async () => { setLoading(true); setError(''); try { setErrors(await api.serverErrors()) } catch (err) { setError(displayError(err)) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const filtered = useMemo(() => errors.filter((item) => (status === 'all' || item.status === status) && (severity === 'all' || item.severity === severity) && `${item.code} ${item.message} ${item.service}`.toLowerCase().includes(query.toLowerCase())), [errors, status, severity, query])
  const updateError = async (item: ServerError, nextStatus: ServerError['status']) => { setWorking(true); try { const updated = await api.updateServerError(item.id, { status: nextStatus, notes: item.notes }); setErrors((current) => current.map((entry) => entry.id === item.id ? { ...entry, ...updated } : entry)); setSelected((current) => current?.id === item.id ? { ...current, ...updated } : current); showToast(nextStatus === 'resolved' ? '오류를 해결됨으로 표시했습니다.' : nextStatus === 'ignored' ? '오류 그룹을 무시 처리했습니다.' : nextStatus === item.status ? '운영 메모를 저장했습니다.' : '오류 상태를 변경했습니다.') } catch (err) { showToast(displayError(err), 'error') } finally { setWorking(false) } }
  const openCount = errors.filter((item) => item.status !== 'resolved' && item.status !== 'ignored').length
  return <AppShell title="오류 · 인시던트" eyebrow="SYSTEM OPERATIONS" actions={<Button variant="secondary" onClick={() => void load()}><RefreshCw size={15} /> 새로고침</Button>}>
    {errors.filter((item) => item.severity === 'critical' && item.status !== 'resolved' && item.status !== 'ignored').slice(0, 1).map((incident) => <div key={incident.id} className="incident-banner incident-critical"><span><Siren size={18} /></span><div><strong>{incident.code} 긴급 인시던트</strong><p>{incident.message}</p></div><Badge tone="danger">{incident.status === 'investigating' ? '조사 중' : '대응 필요'}</Badge><button onClick={() => setSelected(incident)}>상세 보기 <ChevronRight size={14} /></button></div>)}
    <section className="error-stat-grid"><article><span className="metric-icon coral"><CircleAlert size={18} /></span><div><strong>{openCount}</strong><small>표시된 열린 오류</small></div></article><article><span className="metric-icon red"><AlertOctagon size={18} /></span><div><strong>{errors.filter((item) => item.severity === 'critical' && item.status !== 'resolved' && item.status !== 'ignored').length}</strong><small>표시된 긴급 오류</small></div></article><article><span className="metric-icon amber"><Activity size={18} /></span><div><strong>{errors.reduce((sum,item) => sum + item.occurrences, 0).toLocaleString()}</strong><small>표시된 그룹 발생 합계</small></div></article><article><span className="metric-icon mint"><CheckCircle2 size={18} /></span><div><strong>{errors.filter((item) => item.status === 'resolved').length}</strong><small>표시된 해결 그룹</small></div></article></section>
    <section className="admin-panel error-center"><div className="error-toolbar"><div className="filter-tabs"><button className={status === 'open' ? 'active' : ''} onClick={() => setStatus('open')}>열림</button><button className={status === 'investigating' ? 'active' : ''} onClick={() => setStatus('investigating')}>조사 중</button><button className={status === 'resolved' ? 'active' : ''} onClick={() => setStatus('resolved')}>해결됨</button><button className={status === 'all' ? 'active' : ''} onClick={() => setStatus('all')}>전체</button></div><div><div className="search-box"><Search size={16} /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="오류 코드, 메시지 검색" /></div><Select aria-label="심각도로 거르기" value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="all">모든 심각도</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></Select></div></div>
      {loading ? <div className="table-skeleton">오류 이벤트를 불러오는 중…</div> : error ? <ErrorState message={error} onRetry={() => void load()} /> : filtered.length === 0 ? <EmptyState icon={<CheckCircle2 size={25} />} title="조건에 맞는 오류가 없습니다" description="현재 시스템이 안정적으로 운영 중이거나 필터 조건에 맞는 이벤트가 없습니다." /> : <div className="error-list"><div className="error-list-head"><span>오류</span><span>서비스</span><span>발생</span><span>마지막 감지</span><span>상태</span><span /></div>{filtered.map((item) => <button key={item.id} className="error-row" onClick={() => setSelected(item)}><span className={`severity-bar severity-${item.severity}`} /><div className="error-summary"><div><Badge tone={severityTone[item.severity]}>{severityLabel[item.severity]}</Badge><code>{item.code}</code></div><strong>{item.message}</strong><small>{[item.requestId && `Request ${item.requestId}`, item.lastSeenVersion && (item.lastSeenVersion === runningVersion ? `현재 버전 ${item.lastSeenVersion}` : `${item.lastSeenVersion}에서 마지막 발생`)].filter(Boolean).join(' · ')}</small></div><span><Server size={14} /> {item.service || 'api'}</span><strong>{item.occurrences.toLocaleString()}회</strong><span>{relativeDate(item.lastSeenAt)}</span><Badge tone={item.status === 'resolved' ? 'success' : item.status === 'investigating' ? 'info' : 'warning'}>{item.status === 'open' ? '열림' : item.status === 'investigating' ? '조사 중' : item.status === 'resolved' ? '해결됨' : '무시'}</Badge><ChevronRight size={17} /></button>)}</div>}
    </section>
    {selected && <div className="drawer-backdrop" onClick={() => setSelected(null)}><aside ref={drawer as React.RefObject<HTMLElement>} tabIndex={-1} className="error-drawer" onClick={(event) => event.stopPropagation()}><header><div><Badge tone={severityTone[selected.severity]}>{severityLabel[selected.severity]}</Badge><code>{selected.code}</code></div><button className="icon-button" onClick={() => setSelected(null)} aria-label="닫기">×</button></header><section className="error-drawer-title"><h2>{selected.message}</h2><div><Badge tone={selected.status === 'resolved' ? 'success' : 'warning'}>{selected.status}</Badge><span>마지막 감지 {relativeDate(selected.lastSeenAt)}</span></div></section><section className="error-detail-grid"><div><span>서비스</span><strong>{selected.service || 'api'}</strong></div><div><span>발생 횟수</span><strong>{selected.occurrences.toLocaleString()}회</strong></div><div><span>처음 감지</span><strong>{formatDate(selected.firstSeenAt, { year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit' })}</strong></div><div><span>Fingerprint</span><strong>{selected.fingerprint || '—'}</strong></div><div><span>처음 발생 버전</span><strong>{selected.firstSeenVersion || '기록 없음'}</strong></div><div><span>마지막 발생 버전</span><strong>{selected.lastSeenVersion || '기록 없음'}</strong></div></section>{buildNote(selected, runningVersion).text && <p className={`incident-build incident-build-${buildNote(selected, runningVersion).standing}`}>{buildNote(selected, runningVersion).text}</p>}{selected.requestId && <section className="request-id-card"><span>Request ID</span><code>{selected.requestId}</code><button onClick={async () => { await copyText(selected.requestId!); showToast('Request ID를 복사했습니다.') }}><Copy size={14} /></button></section>}<section className="stack-section"><div><strong><TerminalSquare size={16} /> 서버 상세</strong></div><pre>{selected.stack || '보안을 위해 이 오류 그룹에는 서버 스택이 공개되지 않았습니다. Request ID와 운영 로그를 함께 확인하세요.'}</pre></section><section className="stack-section"><div><strong>운영 메모</strong></div><Textarea value={selected.notes || ''} maxLength={4000} onChange={(event) => setSelected({ ...selected, notes: event.target.value })} placeholder="원인, 대응 담당자, 후속 조치 등을 기록하세요." /></section><footer><Button variant="secondary" disabled={working} onClick={() => void updateError(selected, selected.status)}>메모 저장</Button>{selected.status === 'open' && <Button variant="secondary" disabled={working} onClick={() => void updateError(selected, 'investigating')}><Activity size={15} /> 대응 시작</Button>}{selected.status !== 'resolved' && selected.status !== 'ignored' ? <><Button variant="secondary" disabled={working} onClick={() => void updateError(selected, 'ignored')}>무시</Button><Button disabled={working} onClick={() => void updateError(selected, 'resolved')}><Check size={15} /> 해결됨 표시</Button></> : <Button disabled={working} onClick={() => void updateError(selected, 'open')}>다시 열기</Button>}</footer></aside></div>}
  </AppShell>
}
